Repository apache/maven-remote-resources-plugin, pull requests merged in 2024-12, with the labels that each got.

#67 Switch to Guice constructor injection
  pom.xml
  src/main/java/org/apache/maven/plugin/resources/remote/AbstractProcessRemoteResourcesMojo.java
  src/main/java/org/apache/maven/plugin/resources/remote/AggregateProcessRemoteResourcesMojo.java
  src/main/java/org/apache/maven/plugin/resources/remote/ProcessRemoteResourcesMojo.java
Labels: maintenance

#71 [MRRESOURCES-151] Deprecate includeProjectProperties parameter
  src/main/java/org/apache/maven/plugin/resources/remote/AbstractProcessRemoteResourcesMojo.java
Labels: deprecated

#72 Avoid using deprecated API
  src/main/java/org/apache/maven/plugin/resources/remote/AbstractProcessRemoteResourcesMojo.java
  src/main/java/org/apache/maven/plugin/resources/remote/BundleRemoteResourcesMojo.java
Labels: maintenance

#73 Declare used dependencies
  pom.xml
Labels: maintenance

#74 [MRRESOURCES-150] Fix dependencies
  pom.xml
Labels: maintenance

#76 [MRRESOURCES-152] Add property for resourceBundles and outputDirectory
  src/main/java/org/apache/maven/plugin/resources/remote/AbstractProcessRemoteResourcesMojo.java
Labels: enhancement

#77 [MRRESOURCES-153] Bump maven-archiver from 3.6.1 to 3.6.3
  pom.xml
Labels: dependencies

#79 [MRRESOURCES-155] Allow project workspace files to override bundle resources
  src/it/process-project-file/common2.txt
  src/it/process-project-file/invoker.properties
  src/it/process-project-file/pom.xml
  src/it/process-project-file/verify.groovy
  src/main/java/org/apache/maven/plugin/resources/remote/AbstractProcessRemoteResourcesMojo.java
Labels: enhancement
